#!/usr/bin/env bash


ARTIFACT="$ARTIFACT"
MAVEN_PASSWORD="$MAVEN_PASSWORD"
MAVEN_URL="$MAVEN_URL"
MAVEN_USERNAME="$MAVEN_USERNAME"
PARENT="$PARENT"
VERSION="{pom_version}"

curl -X PUT -u $MAVEN_USERNAME:$MAVEN_PASSWORD --upload-file pom.xml $MAVEN_URL/$PARENT/$VERSION/$ARTIFACT-$VERSION.pom
curl -X PUT -u $MAVEN_USERNAME:$MAVEN_PASSWORD --upload-file lib.jar $MAVEN_URL/$PARENT/$VERSION/$ARTIFACT-$VERSION.jar
